-- Final safe movie upload schema guardrail for Admin Add/Edit Content.
-- No data is deleted, reset, dropped, or renamed.

alter table public.movies
  add column if not exists title text,
  add column if not exists slug text,
  add column if not exists type text default 'movie',
  add column if not exists status text default 'draft',
  add column if not exists content_type text default 'movie',
  add column if not exists primary_section text default 'recently_added',
  add column if not exists show_in_hero boolean default false,
  add column if not exists display_title text,
  add column if not exists original_title text,
  add column if not exists description text,
  add column if not exists short_description text,
  add column if not exists release_year integer,
  add column if not exists duration_minutes integer,
  add column if not exists rating numeric,
  add column if not exists imdb_rating numeric,
  add column if not exists language text,
  add column if not exists primary_language text,
  add column if not exists languages_json jsonb default '[]'::jsonb,
  add column if not exists genres_json jsonb default '[]'::jsonb,
  add column if not exists tags_json jsonb default '[]'::jsonb,
  add column if not exists cast_json jsonb default '[]'::jsonb,
  add column if not exists poster_url text,
  add column if not exists banner_url text,
  add column if not exists thumbnail_url text,
  add column if not exists trailer_url text,
  add column if not exists trailer_provider text,
  add column if not exists video_url text,
  add column if not exists video_embed_url text,
  add column if not exists video_provider text default 'direct',
  add column if not exists video_id text,
  add column if not exists official_platform text,
  add column if not exists platform_name text,
  add column if not exists watch_url text,
  add column if not exists platform_home_url text,
  add column if not exists platform_search_url text,
  add column if not exists app_deeplink text,
  add column if not exists open_mode text default 'auto',
  add column if not exists mobile_web_supported text default 'unknown',
  add column if not exists desktop_web_supported text default 'unknown',
  add column if not exists app_required boolean default false,
  add column if not exists play_store_link text,
  add column if not exists play_store_url text,
  add column if not exists app_store_link text,
  add column if not exists app_store_url text,
  add column if not exists fallback_note text,
  add column if not exists quality text,
  add column if not exists availability_type text,
  add column if not exists director text,
  add column if not exists popularity_score numeric default 0,
  add column if not exists is_featured boolean default false,
  add column if not exists is_latest boolean default false,
  add column if not exists is_trending boolean default false,
  add column if not exists is_hindi_dubbed boolean default false,
  add column if not exists is_free_legal boolean default false,
  add column if not exists is_official boolean default false,
  add column if not exists has_licensed_video boolean default false,
  add column if not exists license_type text,
  add column if not exists license_owner_name text,
  add column if not exists license_start_date date,
  add column if not exists license_expiry_date date,
  add column if not exists license_notes text,
  add column if not exists distribution_territory text,
  add column if not exists season_number integer,
  add column if not exists episode_number integer,
  add column if not exists episode_title text,
  add column if not exists playlist_group text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists og_image_url text,
  add column if not exists updated_at timestamptz default now();

notify pgrst, 'reload schema';
